#ifndef BVFS_CONSTANTS_H
#define BVFS_CONSTANTS_H 
 

#define BLOCK_SIZE 512
#define BLOCK_COUNT 16384

#define PARTITION_SIZE (BLOCK_SIZE * BLOCK_COUNT)

#define FILE_BLOCK_COUNT 128
#define MAX_FILE_SIZE = (BLOCK_SIZE * FILE_BLOCK_COUNT)
#define MAX_NUM_FILES 256

 
#endif /* BVFS_CONSTANTS_H */
